### ISSUE TITLE
Update milvus-sdk-java to at least 2.3.2 to allow the usage of http protocol of milvus

### ISSUE THREAD

**Issue by bgeng777** [zilliztech/kafka-connect-milvus#25]
Hi there,
Thanks for creating the kafka connect to milvus!
When I test it locally with a self-hosted milvus and my local kafka cluster, I met such error:
```
ERROR [zilliz-kafka-connect-milvus|task-0] DescribeCollectionRequest RPC failed! (io.milvus.client.AbstractMilvusGrpcClient:3159)
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at io.milvus.grpc.MilvusServiceGrpc$MilvusServiceBlockingStub.describeCollection(MilvusServiceGrpc.java:4421)
	at io.milvus.client.AbstractMilvusGrpcClient.describeCollection(AbstractMilvusGrpcClient.java:687)
	at io.milvus.client.MilvusServiceClient.lambda$describeCollection$9(MilvusServiceClient.java:343)
	at io.milvus.client.MilvusServiceClient.retry(MilvusServiceClient.java:259)
	at io.milvus.client.MilvusServiceClient.describeCollection(MilvusServiceClient.java:343)
	at com.milvus.io.kafka.MilvusSinkTask.GetCollectionInfo(MilvusSinkTask.java:70)
	at com.milvus.io.kafka.MilvusSinkTask.start(MilvusSinkTask.java:52)
	at com.milvus.io.kafka.MilvusSinkTask.start(MilvusSinkTask.java:42)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:329)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.grpc.netty.shaded.io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 485454502f312e31203430302042616420526571756573740d0a436f6e74656e742d547970653a20746578742f706c61696e3b20636861727365743d7574662d380d0a436f6e6e656374696f6e3a20636c6f73650d0a0d0a343030204261642052657175657374
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1213)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```
It shows that SSL/TLS (https) is required but I only provide http endpoint, which should not fall into the https codepath. After some debugging, I think it is a bug in milvus-sdk-java v2.3.1 (see [codes](https://github.com/milvus-io/milvus-sdk-java/blob/v2.3.1/src/main/java/io/milvus/param/ConnectParam.java#L361) here), which wrongly processes all endpoints using https protocol. I find this bug is fixed in v2.3.2 (See [codes](https://github.com/milvus-io/milvus-sdk-java/blob/v2.3.2/src/main/java/io/milvus/param/ConnectParam.java#L361) here).

So I tried to clone kafka-connect-milvus repo and update its pom.xml from
```xml
 <dependency>
        <groupId>io.milvus</groupId>
        <artifactId>milvus-sdk-java</artifactId>
        <version>2.3.1</version>
</dependency>
```
to
```xml
 <dependency>
        <groupId>io.milvus</groupId>
        <artifactId>milvus-sdk-java</artifactId>
        <version>2.3.2</version>
</dependency>
```
Then I rerun the `mvn clean package` command and use the new zip in my local env. Everything works as expected now.
So maybe we can udpate milvus-sdk-java to at least 2.3.2 to allow the usage of http protocol of milvus as well.

**Comment by bgeng777** [comment]
Thanks!
